# CMake generated Testfile for 
# Source directory: C:/Users/DELL/Documents/Project IV/tests
# Build directory: C:/Users/DELL/Documents/Project IV/build_root/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(PacketTests.default_constructor "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/PacketTests.exe" "default_constructor")
  set_tests_properties(PacketTests.default_constructor PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;34;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(PacketTests.default_constructor "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/PacketTests.exe" "default_constructor")
  set_tests_properties(PacketTests.default_constructor PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;34;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(PacketTests.default_constructor "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/PacketTests.exe" "default_constructor")
  set_tests_properties(PacketTests.default_constructor PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;34;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(PacketTests.default_constructor "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/PacketTests.exe" "default_constructor")
  set_tests_properties(PacketTests.default_constructor PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;34;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(PacketTests.default_constructor NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(PacketTests.parameterized_constructor_and_setters "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/PacketTests.exe" "parameterized_constructor_and_setters")
  set_tests_properties(PacketTests.parameterized_constructor_and_setters PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;35;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(PacketTests.parameterized_constructor_and_setters "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/PacketTests.exe" "parameterized_constructor_and_setters")
  set_tests_properties(PacketTests.parameterized_constructor_and_setters PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;35;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(PacketTests.parameterized_constructor_and_setters "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/PacketTests.exe" "parameterized_constructor_and_setters")
  set_tests_properties(PacketTests.parameterized_constructor_and_setters PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;35;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(PacketTests.parameterized_constructor_and_setters "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/PacketTests.exe" "parameterized_constructor_and_setters")
  set_tests_properties(PacketTests.parameterized_constructor_and_setters PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;35;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(PacketTests.parameterized_constructor_and_setters NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(PacketTests.copy_constructor_deep_copy "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/PacketTests.exe" "copy_constructor_deep_copy")
  set_tests_properties(PacketTests.copy_constructor_deep_copy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;36;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(PacketTests.copy_constructor_deep_copy "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/PacketTests.exe" "copy_constructor_deep_copy")
  set_tests_properties(PacketTests.copy_constructor_deep_copy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;36;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(PacketTests.copy_constructor_deep_copy "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/PacketTests.exe" "copy_constructor_deep_copy")
  set_tests_properties(PacketTests.copy_constructor_deep_copy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;36;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(PacketTests.copy_constructor_deep_copy "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/PacketTests.exe" "copy_constructor_deep_copy")
  set_tests_properties(PacketTests.copy_constructor_deep_copy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;36;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(PacketTests.copy_constructor_deep_copy NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(PacketTests.assignment_operator_and_self_assignment "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/PacketTests.exe" "assignment_operator_and_self_assignment")
  set_tests_properties(PacketTests.assignment_operator_and_self_assignment PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;37;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(PacketTests.assignment_operator_and_self_assignment "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/PacketTests.exe" "assignment_operator_and_self_assignment")
  set_tests_properties(PacketTests.assignment_operator_and_self_assignment PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;37;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(PacketTests.assignment_operator_and_self_assignment "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/PacketTests.exe" "assignment_operator_and_self_assignment")
  set_tests_properties(PacketTests.assignment_operator_and_self_assignment PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;37;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(PacketTests.assignment_operator_and_self_assignment "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/PacketTests.exe" "assignment_operator_and_self_assignment")
  set_tests_properties(PacketTests.assignment_operator_and_self_assignment PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;37;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(PacketTests.assignment_operator_and_self_assignment NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(PacketTests.serialize_and_deserialize_round_trip "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/PacketTests.exe" "serialize_and_deserialize_round_trip")
  set_tests_properties(PacketTests.serialize_and_deserialize_round_trip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;38;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(PacketTests.serialize_and_deserialize_round_trip "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/PacketTests.exe" "serialize_and_deserialize_round_trip")
  set_tests_properties(PacketTests.serialize_and_deserialize_round_trip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;38;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(PacketTests.serialize_and_deserialize_round_trip "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/PacketTests.exe" "serialize_and_deserialize_round_trip")
  set_tests_properties(PacketTests.serialize_and_deserialize_round_trip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;38;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(PacketTests.serialize_and_deserialize_round_trip "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/PacketTests.exe" "serialize_and_deserialize_round_trip")
  set_tests_properties(PacketTests.serialize_and_deserialize_round_trip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;38;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(PacketTests.serialize_and_deserialize_round_trip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(PacketTests.empty_payload_paths "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/PacketTests.exe" "empty_payload_paths")
  set_tests_properties(PacketTests.empty_payload_paths PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;39;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(PacketTests.empty_payload_paths "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/PacketTests.exe" "empty_payload_paths")
  set_tests_properties(PacketTests.empty_payload_paths PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;39;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(PacketTests.empty_payload_paths "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/PacketTests.exe" "empty_payload_paths")
  set_tests_properties(PacketTests.empty_payload_paths PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;39;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(PacketTests.empty_payload_paths "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/PacketTests.exe" "empty_payload_paths")
  set_tests_properties(PacketTests.empty_payload_paths PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;39;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(PacketTests.empty_payload_paths NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(PacketTests.deserialize_rejects_invalid_inputs_without_mutating_packet "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/PacketTests.exe" "deserialize_rejects_invalid_inputs_without_mutating_packet")
  set_tests_properties(PacketTests.deserialize_rejects_invalid_inputs_without_mutating_packet PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;40;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(PacketTests.deserialize_rejects_invalid_inputs_without_mutating_packet "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/PacketTests.exe" "deserialize_rejects_invalid_inputs_without_mutating_packet")
  set_tests_properties(PacketTests.deserialize_rejects_invalid_inputs_without_mutating_packet PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;40;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(PacketTests.deserialize_rejects_invalid_inputs_without_mutating_packet "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/PacketTests.exe" "deserialize_rejects_invalid_inputs_without_mutating_packet")
  set_tests_properties(PacketTests.deserialize_rejects_invalid_inputs_without_mutating_packet PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;40;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(PacketTests.deserialize_rejects_invalid_inputs_without_mutating_packet "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/PacketTests.exe" "deserialize_rejects_invalid_inputs_without_mutating_packet")
  set_tests_properties(PacketTests.deserialize_rejects_invalid_inputs_without_mutating_packet PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;40;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(PacketTests.deserialize_rejects_invalid_inputs_without_mutating_packet NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.send_all_and_recv_all "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "send_all_and_recv_all")
  set_tests_properties(NetworkManagerTests.send_all_and_recv_all PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;42;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.send_all_and_recv_all "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "send_all_and_recv_all")
  set_tests_properties(NetworkManagerTests.send_all_and_recv_all PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;42;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.send_all_and_recv_all "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "send_all_and_recv_all")
  set_tests_properties(NetworkManagerTests.send_all_and_recv_all PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;42;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.send_all_and_recv_all "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "send_all_and_recv_all")
  set_tests_properties(NetworkManagerTests.send_all_and_recv_all PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;42;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.send_all_and_recv_all NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.send_all_zero_size_returns_true "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "send_all_zero_size_returns_true")
  set_tests_properties(NetworkManagerTests.send_all_zero_size_returns_true PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;43;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.send_all_zero_size_returns_true "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "send_all_zero_size_returns_true")
  set_tests_properties(NetworkManagerTests.send_all_zero_size_returns_true PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;43;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.send_all_zero_size_returns_true "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "send_all_zero_size_returns_true")
  set_tests_properties(NetworkManagerTests.send_all_zero_size_returns_true PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;43;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.send_all_zero_size_returns_true "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "send_all_zero_size_returns_true")
  set_tests_properties(NetworkManagerTests.send_all_zero_size_returns_true PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;43;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.send_all_zero_size_returns_true NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.recv_all_zero_size_returns_true "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "recv_all_zero_size_returns_true")
  set_tests_properties(NetworkManagerTests.recv_all_zero_size_returns_true PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;44;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.recv_all_zero_size_returns_true "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "recv_all_zero_size_returns_true")
  set_tests_properties(NetworkManagerTests.recv_all_zero_size_returns_true PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;44;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.recv_all_zero_size_returns_true "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "recv_all_zero_size_returns_true")
  set_tests_properties(NetworkManagerTests.recv_all_zero_size_returns_true PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;44;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.recv_all_zero_size_returns_true "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "recv_all_zero_size_returns_true")
  set_tests_properties(NetworkManagerTests.recv_all_zero_size_returns_true PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;44;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.recv_all_zero_size_returns_true NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.recv_all_multiple_iterations "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "recv_all_multiple_iterations")
  set_tests_properties(NetworkManagerTests.recv_all_multiple_iterations PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;45;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.recv_all_multiple_iterations "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "recv_all_multiple_iterations")
  set_tests_properties(NetworkManagerTests.recv_all_multiple_iterations PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;45;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.recv_all_multiple_iterations "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "recv_all_multiple_iterations")
  set_tests_properties(NetworkManagerTests.recv_all_multiple_iterations PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;45;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.recv_all_multiple_iterations "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "recv_all_multiple_iterations")
  set_tests_properties(NetworkManagerTests.recv_all_multiple_iterations PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;45;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.recv_all_multiple_iterations NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.send_packet_and_receive_packet "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "send_packet_and_receive_packet")
  set_tests_properties(NetworkManagerTests.send_packet_and_receive_packet PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;46;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.send_packet_and_receive_packet "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "send_packet_and_receive_packet")
  set_tests_properties(NetworkManagerTests.send_packet_and_receive_packet PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;46;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.send_packet_and_receive_packet "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "send_packet_and_receive_packet")
  set_tests_properties(NetworkManagerTests.send_packet_and_receive_packet PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;46;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.send_packet_and_receive_packet "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "send_packet_and_receive_packet")
  set_tests_properties(NetworkManagerTests.send_packet_and_receive_packet PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;46;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.send_packet_and_receive_packet NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.send_packet_and_receive_packet_with_empty_payload "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "send_packet_and_receive_packet_with_empty_payload")
  set_tests_properties(NetworkManagerTests.send_packet_and_receive_packet_with_empty_payload PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;47;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.send_packet_and_receive_packet_with_empty_payload "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "send_packet_and_receive_packet_with_empty_payload")
  set_tests_properties(NetworkManagerTests.send_packet_and_receive_packet_with_empty_payload PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;47;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.send_packet_and_receive_packet_with_empty_payload "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "send_packet_and_receive_packet_with_empty_payload")
  set_tests_properties(NetworkManagerTests.send_packet_and_receive_packet_with_empty_payload PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;47;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.send_packet_and_receive_packet_with_empty_payload "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "send_packet_and_receive_packet_with_empty_payload")
  set_tests_properties(NetworkManagerTests.send_packet_and_receive_packet_with_empty_payload PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;47;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.send_packet_and_receive_packet_with_empty_payload NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.send_all_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "send_all_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.send_all_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;48;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.send_all_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "send_all_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.send_all_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;48;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.send_all_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "send_all_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.send_all_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;48;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.send_all_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "send_all_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.send_all_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;48;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.send_all_failure_on_invalid_socket NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.send_packet_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "send_packet_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.send_packet_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;49;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.send_packet_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "send_packet_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.send_packet_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;49;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.send_packet_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "send_packet_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.send_packet_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;49;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.send_packet_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "send_packet_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.send_packet_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;49;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.send_packet_failure_on_invalid_socket NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.recv_all_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "recv_all_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.recv_all_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;50;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.recv_all_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "recv_all_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.recv_all_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;50;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.recv_all_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "recv_all_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.recv_all_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;50;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.recv_all_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "recv_all_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.recv_all_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;50;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.recv_all_failure_on_invalid_socket NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.receive_packet_header_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "receive_packet_header_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.receive_packet_header_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;51;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.receive_packet_header_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "receive_packet_header_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.receive_packet_header_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;51;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.receive_packet_header_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "receive_packet_header_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.receive_packet_header_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;51;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.receive_packet_header_failure_on_invalid_socket "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "receive_packet_header_failure_on_invalid_socket")
  set_tests_properties(NetworkManagerTests.receive_packet_header_failure_on_invalid_socket PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;51;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.receive_packet_header_failure_on_invalid_socket NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_checksum "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "receive_packet_rejects_invalid_checksum")
  set_tests_properties(NetworkManagerTests.receive_packet_rejects_invalid_checksum PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;52;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_checksum "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "receive_packet_rejects_invalid_checksum")
  set_tests_properties(NetworkManagerTests.receive_packet_rejects_invalid_checksum PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;52;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_checksum "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "receive_packet_rejects_invalid_checksum")
  set_tests_properties(NetworkManagerTests.receive_packet_rejects_invalid_checksum PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;52;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_checksum "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "receive_packet_rejects_invalid_checksum")
  set_tests_properties(NetworkManagerTests.receive_packet_rejects_invalid_checksum PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;52;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_checksum NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_magic "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "receive_packet_rejects_invalid_magic")
  set_tests_properties(NetworkManagerTests.receive_packet_rejects_invalid_magic PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;53;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_magic "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "receive_packet_rejects_invalid_magic")
  set_tests_properties(NetworkManagerTests.receive_packet_rejects_invalid_magic PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;53;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_magic "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "receive_packet_rejects_invalid_magic")
  set_tests_properties(NetworkManagerTests.receive_packet_rejects_invalid_magic PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;53;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_magic "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "receive_packet_rejects_invalid_magic")
  set_tests_properties(NetworkManagerTests.receive_packet_rejects_invalid_magic PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;53;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_magic NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_version "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "receive_packet_rejects_invalid_version")
  set_tests_properties(NetworkManagerTests.receive_packet_rejects_invalid_version PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;54;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_version "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "receive_packet_rejects_invalid_version")
  set_tests_properties(NetworkManagerTests.receive_packet_rejects_invalid_version PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;54;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_version "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "receive_packet_rejects_invalid_version")
  set_tests_properties(NetworkManagerTests.receive_packet_rejects_invalid_version PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;54;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_version "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "receive_packet_rejects_invalid_version")
  set_tests_properties(NetworkManagerTests.receive_packet_rejects_invalid_version PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;54;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.receive_packet_rejects_invalid_version NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NetworkManagerTests.receive_packet_fails_on_incomplete_payload "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/NetworkManagerTests.exe" "receive_packet_fails_on_incomplete_payload")
  set_tests_properties(NetworkManagerTests.receive_packet_fails_on_incomplete_payload PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;55;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NetworkManagerTests.receive_packet_fails_on_incomplete_payload "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe" "receive_packet_fails_on_incomplete_payload")
  set_tests_properties(NetworkManagerTests.receive_packet_fails_on_incomplete_payload PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;55;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NetworkManagerTests.receive_packet_fails_on_incomplete_payload "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/NetworkManagerTests.exe" "receive_packet_fails_on_incomplete_payload")
  set_tests_properties(NetworkManagerTests.receive_packet_fails_on_incomplete_payload PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;55;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NetworkManagerTests.receive_packet_fails_on_incomplete_payload "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/NetworkManagerTests.exe" "receive_packet_fails_on_incomplete_payload")
  set_tests_properties(NetworkManagerTests.receive_packet_fails_on_incomplete_payload PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;31;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;55;add_named_case;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(NetworkManagerTests.receive_packet_fails_on_incomplete_payload NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(AllServerTests "C:/Users/DELL/Documents/Project IV/build_root/tests/Debug/Test_Server.exe")
  set_tests_properties(AllServerTests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;68;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(AllServerTests "C:/Users/DELL/Documents/Project IV/build_root/tests/Release/Test_Server.exe")
  set_tests_properties(AllServerTests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;68;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(AllServerTests "C:/Users/DELL/Documents/Project IV/build_root/tests/MinSizeRel/Test_Server.exe")
  set_tests_properties(AllServerTests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;68;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(AllServerTests "C:/Users/DELL/Documents/Project IV/build_root/tests/RelWithDebInfo/Test_Server.exe")
  set_tests_properties(AllServerTests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;68;add_test;C:/Users/DELL/Documents/Project IV/tests/CMakeLists.txt;0;")
else()
  add_test(AllServerTests NOT_AVAILABLE)
endif()
