set(__QT_DEPLOY_TARGET_ClientApp_FILE C:/Users/DELL/Documents/Project IV/build_root/bin/Release/ClientApp.exe)
set(__QT_DEPLOY_TARGET_ClientApp_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_ClientApp_RUNTIME_DLLS C:/Qt/6.11.0/msvc2022_64/bin/Qt6Widgets.dll;C:/Qt/6.11.0/msvc2022_64/bin/Qt6Gui.dll;C:/Qt/6.11.0/msvc2022_64/bin/Qt6Core.dll)
set(__QT_DEPLOY_TARGET_server_lib_FILE C:/Users/DELL/Documents/Project IV/build_root/src/server/Release/server_lib.lib)
set(__QT_DEPLOY_TARGET_server_lib_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_ServerApp_FILE C:/Users/DELL/Documents/Project IV/build_root/src/server/Release/ServerApp.exe)
set(__QT_DEPLOY_TARGET_ServerApp_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_ServerApp_RUNTIME_DLLS C:/Qt/6.11.0/msvc2022_64/bin/Qt6Widgets.dll;C:/Qt/6.11.0/msvc2022_64/bin/Qt6Gui.dll;C:/Qt/6.11.0/msvc2022_64/bin/Qt6Core.dll)
set(__QT_DEPLOY_TARGET_PacketTests_FILE C:/Users/DELL/Documents/Project IV/build_root/tests/Release/PacketTests.exe)
set(__QT_DEPLOY_TARGET_PacketTests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_PacketTests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_NetworkManagerTests_FILE C:/Users/DELL/Documents/Project IV/build_root/tests/Release/NetworkManagerTests.exe)
set(__QT_DEPLOY_TARGET_NetworkManagerTests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_NetworkManagerTests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_Test_Server_FILE C:/Users/DELL/Documents/Project IV/build_root/tests/Release/Test_Server.exe)
set(__QT_DEPLOY_TARGET_Test_Server_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_Test_Server_RUNTIME_DLLS )
